### ISSUE TITLE
I got a problem whem node scripts/deploy.js

### ISSUE THREAD

**Issue by 2jaeeeee** [wikibook/hyperledger-fabric#1]
![0518](https://user-images.githubusercontent.com/50053772/57965430-2b8d5180-797f-11e9-9f18-d428458d636e.JPG)

**Comment by 2jaeeeee** [comment]
![image](https://user-images.githubusercontent.com/50053772/57967039-e83ddd80-7994-11e9-9992-c2c4b40dc426.png)
and this error too...help TT

**Comment by wikibook** [comment]
안녕하세요. 위키북스 출판사입니다. 보내주신 문의사항을 역자분께 전달했고, 다음과 같은 답신을 받았습니다. 참고 부탁드립니다. 감사합니다.

> 벤더링후 GOPATH 설정이 잘못된 것으로 보입니다.
> 항목 4.3.29를 참조하여 다시 실행해 주시기 바랍니다.
