### ISSUE TITLE
public/index.html 존재여부

### ISSUE THREAD

**Issue by eyPark0** [wikibook/hyperledger-fabric#4]
안녕하세요.

튜토리얼을 따라 실행하던 중 npm start 이후 localhost로 접속 후 로그인 시 그림과 같은 에러가 발생하여 문의드립니다.
public/index.html 파일은 예제코드로 제공되지 않는 건가요?

![image](https://github.com/wikibook/hyperledger-fabric/assets/65988447/6deb702e-5f12-4c98-85b7-be5ee140e3ee)

답변주시면 감사드리겠습니다.

**Comment by eyPark0** [comment]
해결하였습니다.

npm run build를 실행하지 않았기 때문이였네요.

![image](https://github.com/wikibook/hyperledger-fabric/assets/65988447/89a3560e-870a-47d6-b4ec-0ba3be8ef4cf)

![image](https://github.com/wikibook/hyperledger-fabric/assets/65988447/1192a279-f51d-4c9e-bd3b-816b13b8c259)

**Comment by wikibook** [comment]
안녕하세요. 위키북스 담당자입니다.
말씀해 주신 사항을 역자분께 확인 요청드렸었는데 그 사이에 해결하셨네요. ^^
해결되어 다행이고요, 처리하신 사항을 공유해 주셔서 감사합니다.
오늘도 좋은 하루 보내세요..!
